name = "MushroomBody"
uuid = "e80a2894-e75f-42b0-bb72-3b55f5f7298e"
authors = ["james-a-mcmanus"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
